// package main

// import (
// 	"context"
// 	"fmt"
// 	"log"
// 	"net"
// 	"time"

// 	// These are AUTO-GENERATED by protoc from your .proto files
// 	pb "grpc-demo/proto/userpb"

// 	"google.golang.org/grpc"
// 	"google.golang.org/grpc/codes"
// 	"google.golang.org/grpc/status"
// )

// // ═══════════════════════════════════════════════════════════════
// // STEP 1: Define your server struct
// // It must embed the "Unimplemented" server — this is REQUIRED by gRPC
// // so that if you add new RPCs later, old servers don't break.
// // ═══════════════════════════════════════════════════════════════

// type userServer struct {
// 	pb.UnimplementedUserServiceServer // <-- MUST embed this

// 	// Fake in-memory database
// 	users map[int32]*pb.User
// }

// // ═══════════════════════════════════════════════════════════════
// // STEP 2: Implement each RPC method from the proto service
// // ═══════════════════════════════════════════════════════════════

// // --- Unary RPC: GetUser ---
// // Client sends ONE request, server sends ONE response
// func (s *userServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.User, error) {
// 	log.Printf("📨 GetUser called with ID: %d", req.Id)

// 	user, exists := s.users[req.Id]
// 	if !exists {
// 		// gRPC uses its own error codes (NOT HTTP codes)
// 		// Common codes: NotFound, InvalidArgument, Internal, PermissionDenied
// 		return nil, status.Errorf(codes.NotFound, "user with ID %d not found", req.Id)
// 	}

// 	return user, nil
// }

// // --- Server Streaming RPC: ListUsers ---
// // Client sends ONE request, server sends MULTIPLE responses (a stream)
// func (s *userServer) ListUsers(req *pb.Empty, stream pb.UserService_ListUsersServer) error {
// 	log.Println("📨 ListUsers called — streaming all users...")

// 	for _, user := range s.users {
// 		// Send each user one at a time through the stream
// 		if err := stream.Send(user); err != nil {
// 			return err
// 		}
// 		// Small delay to show streaming in action
// 		time.Sleep(500 * time.Millisecond)
// 	}

// 	return nil // returning nil closes the stream
// }

// // ═══════════════════════════════════════════════════════════════
// // STEP 3: Create the gRPC server and start listening
// // ═══════════════════════════════════════════════════════════════

// func main() {
// 	// 3a. Create a TCP listener
// 	lis, err := net.Listen("tcp", ":50051")
// 	if err != nil {
// 		log.Fatalf("❌ Failed to listen: %v", err)
// 	}

// 	// 3b. Create a new gRPC server instance
// 	grpcServer := grpc.NewServer()

// 	// 3c. Register our service implementation with the gRPC server
// 	pb.RegisterUserServiceServer(grpcServer, &userServer{
// 		users: map[int32]*pb.User{
// 			1: {Id: 1, Name: "Alice", Email: "alice@example.com"},
// 			2: {Id: 2, Name: "Bob", Email: "bob@example.com"},
// 			3: {Id: 3, Name: "Charlie", Email: "charlie@example.com"},
// 		},
// 	})

// 	// 3d. Start serving
// 	fmt.Println("🚀 User Service running on :50051")
// 	if err := grpcServer.Serve(lis); err != nil {
// 		log.Fatalf("❌ Failed to serve: %v", err)
// 	}
// }
package main

func main() {
	
}